<a href="https://colab.research.google.com/github/LeafarxC/aula_dados_analytics_python/blob/main/projeto_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [4]:
#importar o CSV
df_vendas = pd.read_csv('/content/Vendas.csv')

In [9]:
df_vendas.head()

   ID_Venda         Produto  Quantidade  Preco_Unitario  Data_Venda
0         1   Cadeira Gamer          29         1202.86  2023-05-01
1         2  Roteador Wi-Fi          17          737.71  2025-10-02
2         3  Roteador Wi-Fi          12          760.47  2023-04-28
3         4   Cadeira Gamer           4          875.04  2024-09-30
4         5   Controle Xbox          23          967.56  2024-06-09

In [10]:
df_vendas.tail()

     ID_Venda         Produto  Quantidade  Preco_Unitario  Data_Venda
995       996      Impressora          11          878.36  2024-04-20
996       997       Óculos VR           3         1173.65  2024-08-23
997       998  Fone de ouvido          13          109.07  2024-08-11
998       999  HD Externo 1TB          16          691.38  2023-07-05
999      1000  Câmera Digital           7         1201.48  2024-07-03

In [11]:
df_vendas.describe()

          ID_Venda  Quantidade  Preco_Unitario
count  1000.000000   1000.0000     1000.000000
mean    500.500000     15.2180      762.092790
std     288.819436      8.2034      429.833655
min       1.000000      1.0000       21.630000
25%     250.750000      8.0000      390.687500
50%     500.500000     15.0000      761.285000
75%     750.250000     22.0000     1136.905000
max    1000.000000     29.0000     1498.950000

In [12]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Venda        1000 non-null   int64
 1   Produto         1000 non-null   object
 2   Quantidade      1000 non-null   int64
 3   Preco_Unitario  1000 non-null   float64
 4   Data_Venda      1000 non-null   object
dtypes: float64(1), int64(2), object(2)
memory usage: 39.2+ KB

In [13]:
df_vendas.head()

   ID_Venda         Produto  Quantidade  Preco_Unitario  Data_Venda
0         1   Cadeira Gamer          29         1202.86  2023-05-01
1         2  Roteador Wi-Fi          17          737.71  2025-10-02
2         3  Roteador Wi-Fi          12          760.47  2023-04-28
3         4   Cadeira Gamer           4          875.04  2024-09-30
4         5   Controle Xbox          23          967.56  2024-06-09

In [14]:
# Preço final - quantidade * preço Unitário
df_vendas['Receita_total'] = df_vendas['Quantidade'] * df_vendas['Preco_Unitario']

In [15]:
df_vendas.head()

,ID_Venda,Produto,Quantidade,Preco_Unitario,Data_Venda,Receita_total
0,1,Cadeira Gamer,29,1202.86,2023-05-01,34882.94
1,2,Roteador Wi-Fi,17,737.71,2025-10-02,12541.07
2,3,Roteador Wi-Fi,12,760.47,2023-04-28,9125.64
3,4,Cadeira Gamer,4,875.04,2024-09-30,3500.16
4,5,Controle Xbox,23,967.56,2024-06-09,22253.88

In [16]:
#Selecionar apenas as colunas - Produtos e receitra total;
df_vendas[['Produto','Receita_total']].head()

          Produto  Receita_total
0   Cadeira Gamer       34882.94
1  Roteador Wi-Fi       12541.07
2  Roteador Wi-Fi        9125.64
3   Cadeira Gamer        3500.16
4   Controle Xbox       22253.88

In [6]:
#linhas onde a quantidade e maior que 20
df_vendas[df_vendas['Quantidade'] > 20]

     ID_Venda         Produto  Quantidade  Preco_Unitario  Data_Venda
0           1   Cadeira Gamer          29         1202.86  2023-05-01
4           5   Controle Xbox          23          967.56  2024-06-09
15         16   Cadeira Gamer          25         1050.08  2024-11-02
17         18   Cadeira Gamer          21         1359.72  2024-08-28
18         19  Câmera Digital          26          476.79  2023-10-29
..        ...             ...         ...             ...         ...
985       986  Placa de Vídeo          24           72.57  2023-08-28
986       987  HD Externo 1TB          22         1411.74  2025-04-27
988       989       Microfone          22          397.40  2023-04-11
990       991       Óculos VR          21          608.09  2023-07-22
994       995  Roteador Wi-Fi          23          944.64  2025-06-26

[311 rows x 5 columns]

In [17]:
#loc (selecionar linhas e colunas por rótulo (produto = 'monitor'))
df_vendas.loc[df_vendas['Produto'] == 'Monitor', ['ID_Venda', 'Quantidade', 'Preco_Unitario', 'Receita_total']]

     ID_Venda  Quantidade  Preco_Unitario  Receita_total
28         29          10          331.83        3318.30
54         55          28           88.17        2468.76
138       139           6          951.61        5709.66
170       171           5         1399.88        6999.40
185       186          27          647.74       17488.98
209       210          26         1108.54       28822.04
217       218          16         1460.47       23367.52
248       249          11         1284.64       14131.04
263       264          13         1260.49       16386.37
268       269          22         1008.94       22196.68
269       270           7         1418.24        9927.68
281       282          14          525.42        7355.88
292       293          12           87.05        1044.60
306       307          29          370.04       10731.16
315       316          21          578.89       12156.69
341       342          19         1484.39       28203.41
419       420          23         1430.06       32891.38
465       466          23         1247.25       28686.75
492       493          19          855.51       16254.69
529       530           3          681.23        2043.69
535       536          25          463.01       11575.25
564       565          29         1354.67       39285.43
585       586          18          537.71        9678.78
604       605          29          609.60       17678.40
661       662           9         1376.04       12384.36
740       741          27          788.35       21285.45
763       764           3         1099.79        3299.37
773       774          29         1258.02       36482.58
798       799          11          759.60        8355.60
875       876          17         1040.08       17681.36
915       916           4         1213.50        4854.00
926       927           8          471.74        3773.92
971       972          19          487.67        9265.73

In [18]:
#selecionar as primeiras 3 linhas e as colunas de 1 a 3
df_vendas.iloc[:3, 1:3]

          Produto  Quantidade
0   Cadeira Gamer          29
1  Roteador Wi-Fi          17
2  Roteador Wi-Fi          12

In [19]:
#calculos (pandas e numpy) descobrir a receita total

print(f"Rceita total de vendas da loja: {df_vendas['Receita_total'].sum():.2f}") # .2f - 2 casas decimais

Rceita total de vendas da loja: 11610833.99

In [20]:
#preço médio unitário dos produtos
print(f"Preço médio dos produtos: {df_vendas['Preco_Unitario'].mean():.2f}")

Preço médio dos produtos: 762.09

In [21]:
#quantidade minima e máxima de produtos vendidos
print(f"Quantidade mínima de produtos vendidos: {df_vendas['Quantidade'].min()}")
print(f"Quantidade máxima de produtos vendidos: {df_vendas['Quantidade'].max()}")

Quantidade mínima de produtos vendidos: 1
Quantidade máxima de produtos vendidos: 29

In [22]:
#simular valores ausentes dentro do df
df_vendas_com_nan = df_vendas.copy() #novo dataframe, foi feito uma copia
df_vendas_com_nan.loc[df_vendas_com_nan.sample(frac=0.05).index, 'Preco_Unitario'] = np.nan
df_vendas_com_nan.loc[df_vendas_com_nan.sample(frac=0.03).index, 'Quantidade'] = np.nan

In [23]:
df_vendas_com_nan.head()

,ID_Venda,Produto,Quantidade,Preco_Unitario,Data_Venda,Receita_total
0,1,Cadeira Gamer,29.0,1202.86,2023-05-01,34882.94
1,2,Roteador Wi-Fi,17.0,737.71,2025-10-02,12541.07
2,3,Roteador Wi-Fi,12.0,760.47,2023-04-28,9125.64
3,4,Cadeira Gamer,NaN,875.04,2024-09-30,3500.16
4,5,Controle Xbox,23.0,967.56,2024-06-09,22253.88

In [24]:
df_vendas_com_nan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Venda        1000 non-null   int64
 1   Produto         1000 non-null   object
 2   Quantidade      970 non-null    float64
 3   Preco_Unitario  950 non-null    float64
 4   Data_Venda      1000 non-null   object
 5   Receita_total   1000 non-null   float64
dtypes: float64(3), int64(1), object(2)
memory usage: 47.0+ KB

In [25]:
df_vendas_com_nan.isna().sum()

ID_Venda           0
Produto            0
Quantidade        30
Preco_Unitario    50
Data_Venda         0
Receita_total      0
dtype: int64

In [26]:
#Preencher com a media os valores NAN da coluna quantidade
df_vendas_pr = df_vendas_com_nan.copy()
media_qtd = df_vendas_pr['Quantidade'].mean()
df_vendas_pr['Quantidade'].fillna(media_qtd, inplace=True)

/tmp/ipython-input-682421733.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_vendas_pr['Quantidade'].fillna(media_qtd, inplace=True)

In [27]:
df_vendas_pr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Venda        1000 non-null   int64
 1   Produto         1000 non-null   object
 2   Quantidade      1000 non-null   float64
 3   Preco_Unitario  950 non-null    float64
 4   Data_Venda      1000 non-null   object
 5   Receita_total   1000 non-null   float64
dtypes: float64(3), int64(1), object(2)
memory usage: 47.0+ KB

In [28]:
#remover os valores ausentes
df_vendas_lp = df_vendas_pr.dropna(subset=['Preco_Unitario'])

In [29]:
df_vendas_lp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 950 entries, 0 to 998
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Venda        950 non-null    int64
 1   Produto         950 non-null    object
 2   Quantidade      950 non-null    float64
 3   Preco_Unitario  950 non-null    float64
 4   Data_Venda      950 non-null    object
 5   Receita_total   950 non-null    float64
dtypes: float64(3), int64(1), object(2)
memory usage: 52.0+ KB

In [30]:
df_vendas_lp.head()

,ID_Venda,Produto,Quantidade,Preco_Unitario,Data_Venda,Receita_total
0,1,Cadeira Gamer,29.00000,1202.86,2023-05-01,34882.94
1,2,Roteador Wi-Fi,17.00000,737.71,2025-10-02,12541.07
2,3,Roteador Wi-Fi,12.00000,760.47,2023-04-28,9125.64
3,4,Cadeira Gamer,15.16701,875.04,2024-09-30,3500.16
4,5,Controle Xbox,23.00000,967.56,2024-06-09,22253.88

In [31]:
vendas_por_produto = df_vendas_lp.groupby('Produto').agg(
    Quantidade_Total=('Quantidade', 'sum'),
    Receita_Total=('Receita_total', 'sum'),
).reset_index()

In [32]:
print(vendas_por_produto)

            Produto  Quantidade_Total  Receita_Total
0     Cadeira Gamer        701.334021      570275.98
1      Caixa de Som        804.334021      659914.81
2      Controle PS5        603.334021      424484.24
3     Controle Xbox        798.000000      670722.77
4    Câmera Digital        927.000000      658293.00
5    Fone de ouvido        550.000000      363572.84
6    HD Externo 1TB        979.334021      758703.62
7        Impressora        622.334021      521380.64
8   Memória RAM 8GB        654.167010      510921.57
9        Mesa Gamer        702.501031      513079.73
10        Microfone        726.501031      472709.67
11          Monitor        519.501031      454164.89
12            Mouse        754.334021      669788.75
13   Placa de Vídeo        721.000000      592607.36
14      Processador        430.167010      293444.42
15   Roteador Wi-Fi        775.167010      568017.55
16        SSD 256GB        783.334021      653807.05
17          Teclado        804.167010      545619.38
18           Webcam        632.000000      423984.36
19        Óculos VR        808.334021      644410.65

In [33]:
#OPrdenar os valores por quantidade total para saber a quantidade mais vendida
produto_mais_vendido = vendas_por_produto.sort_values(by='Quantidade_Total', ascending=False).iloc[0]
print(produto_mais_vendido)

Produto             HD Externo 1TB
Quantidade_Total        979.334021
Receita_Total            758703.62
Name: 6, dtype: object

In [34]:
#Ordenar os valores por receita total para saber o maior valor total gerado
produto_maior_receita = vendas_por_produto.sort_values(by='Receita_Total', ascending=False).iloc[0]
print(produto_maior_receita)

Produto             HD Externo 1TB
Quantidade_Total        979.334021
Receita_Total            758703.62
Name: 6, dtype: object

In [2]:
df_produtos = pd.read_csv('/content/Produtos.csv')

In [3]:
df_produtos.head()

          Produto    Categoria
0         Teclado  Periféricos
1           Mouse  Periféricos
2         Monitor    Monitores
3          Webcam  Periféricos
4  Fone de ouvido        Áudio

In [35]:
#converter a coluna Data venda para tipo correto data
df_vendas_lp['Data_Venda'] = pd.to_datetime(df_vendas_lp['Data_Venda'])

/tmp/ipython-input-915812205.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vendas_lp['Data_Venda'] = pd.to_datetime(df_vendas_lp['Data_Venda'])

In [36]:
df_vendas_lp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 950 entries, 0 to 998
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Venda        950 non-null    int64
 1   Produto         950 non-null    object
 2   Quantidade      950 non-null    float64
 3   Preco_Unitario  950 non-null    float64
 4   Data_Venda      950 non-null    datetime64[ns]
 5   Receita_total   950 non-null    float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(1)
memory usage: 84.2+ KB

In [37]:
#analisar as vendas por mês
df_vendas_lp['Mes_Venda'] = df_vendas_lp['Data_Venda'].dt.month

/tmp/ipython-input-2029255009.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vendas_lp['Mes_Venda'] = df_vendas_lp['Data_Venda'].dt.month

In [38]:
df_vendas_lp.head()

,ID_Venda,Produto,Quantidade,Preco_Unitario,Data_Venda,Receita_total,Mes_Venda
0,1,Cadeira Gamer,29.00000,1202.86,2023-05-01,34882.94,5
1,2,Roteador Wi-Fi,17.00000,737.71,2025-10-02,12541.07,10
2,3,Roteador Wi-Fi,12.00000,760.47,2023-04-28,9125.64,4
3,4,Cadeira Gamer,15.16701,875.04,2024-09-30,3500.16,9
4,5,Controle Xbox,23.00000,967.56,2024-06-09,22253.88,6

In [40]:
venda_por_mes = df_vendas_lp.groupby('Mes_Venda')['Receita_total'].sum().reset_index()

In [41]:
print(venda_por_mes)

    Mes_Venda  Receita_total
0           1      979763.84
1           2     1243124.51
2           3      904106.06
3           4      904735.78
4           5     1069387.47
5           6      939131.87
6           7      845775.71
7           8     1042757.38
8           9     1016230.64
9          10      878322.23
10         11      565058.43
11         12      581509.36

In [42]:
print(df_produtos)

            Produto      Categoria
0           Teclado    Periféricos
1             Mouse    Periféricos
2           Monitor      Monitores
3            Webcam    Periféricos
4    Fone de ouvido          Áudio
5         SSD 256GB  Armazenamento
6    HD Externo 1TB  Armazenamento
7    Placa de Vídeo    Componentes
8       Processador    Componentes
9   Memória RAM 8GB    Componentes
10   Roteador Wi-Fi          Redes
11       Impressora    Periféricos
12   Câmera Digital        Câmeras
13        Microfone          Áudio
14     Caixa de Som          Áudio
15       Mesa Gamer         Móveis
16    Cadeira Gamer         Móveis
17    Controle Xbox          Games
18     Controle PS5          Games
19        Óculos VR          Games

In [43]:
df_merge = pd.merge(df_vendas_lp, df_produtos, on='Produto', how='left')

In [44]:
print(df_merge)

     ID_Venda         Produto  Quantidade  Preco_Unitario Data_Venda  \
0           1   Cadeira Gamer    29.00000         1202.86 2023-05-01
1           2  Roteador Wi-Fi    17.00000          737.71 2025-10-02
2           3  Roteador Wi-Fi    12.00000          760.47 2023-04-28
3           4   Cadeira Gamer    15.16701          875.04 2024-09-30
4           5   Controle Xbox    23.00000          967.56 2024-06-09
..        ...             ...         ...             ...        ...
945       995  Roteador Wi-Fi    23.00000          944.64 2025-06-26
946       996      Impressora    11.00000          878.36 2024-04-20
947       997       Óculos VR     3.00000         1173.65 2024-08-23
948       998  Fone de ouvido    13.00000          109.07 2024-08-11
949       999  HD Externo 1TB    16.00000          691.38 2023-07-05

     Receita_total  Mes_Venda      Categoria
0         34882.94          5         Móveis
1         12541.07         10          Redes
2          9125.64          4          Redes
3          3500.16          9         Móveis
4         22253.88          6          Games
..             ...        ...            ...
945       21726.72          6          Redes
946        9661.96          4    Periféricos
947        3520.95          8          Games
948        1417.91          8          Áudio
949       11062.08          7  Armazenamento

[950 rows x 8 columns]

In [45]:
#Analise de vendas por categoria
vendas_por_categoria = df_merge.groupby('Categoria')['Receita_total'].sum().reset_index()

In [46]:
print(vendas_por_categoria)

       Categoria  Receita_total
0  Armazenamento     1412510.67
1    Componentes     1396973.35
2        Câmeras      658293.00
3          Games     1739617.66
4      Monitores      454164.89
5         Móveis     1083355.71
6    Periféricos     2160773.13
7          Redes      568017.55
8          Áudio     1496197.32

In [47]:
#filtros dentro do DataFrame
df_merge.head()

,ID_Venda,Produto,Quantidade,Preco_Unitario,Data_Venda,Receita_total,Mes_Venda,Categoria
0,1,Cadeira Gamer,29.00000,1202.86,2023-05-01,34882.94,5,Móveis
1,2,Roteador Wi-Fi,17.00000,737.71,2025-10-02,12541.07,10,Redes
2,3,Roteador Wi-Fi,12.00000,760.47,2023-04-28,9125.64,4,Redes
3,4,Cadeira Gamer,15.16701,875.04,2024-09-30,3500.16,9,Móveis
4,5,Controle Xbox,23.00000,967.56,2024-06-09,22253.88,6,Games

In [48]:
#filtrar por coluna ( Produto, quantidade, receita  total)
df_colunas_filtradas = df_merge.filter(items=['Produto', 'Quantidade', 'Receita_total'])

In [49]:
print(df_colunas_filtradas)

            Produto  Quantidade  Receita_total
0     Cadeira Gamer    29.00000       34882.94
1    Roteador Wi-Fi    17.00000       12541.07
2    Roteador Wi-Fi    12.00000        9125.64
3     Cadeira Gamer    15.16701        3500.16
4     Controle Xbox    23.00000       22253.88
..              ...         ...            ...
945  Roteador Wi-Fi    23.00000       21726.72
946      Impressora    11.00000        9661.96
947       Óculos VR     3.00000        3520.95
948  Fone de ouvido    13.00000        1417.91
949  HD Externo 1TB    16.00000       11062.08

[950 rows x 3 columns]

In [52]:
#filtragem mais avançada
df_query = df_merge.query('Produto == "Teclado" and Quantidade > 10')

In [53]:
print(df_query)

     ID_Venda  Produto  Quantidade  Preco_Unitario Data_Venda  Receita_total  \
62         70  Teclado    23.00000         1159.02 2025-03-18       26657.46
63         72  Teclado    27.00000           94.04 2025-07-17        2539.08
97        108  Teclado    15.16701          715.91 2024-03-17       18613.66
108       119  Teclado    25.00000          100.25 2024-10-28        2506.25
114       125  Teclado    18.00000          289.54 2024-10-01        5211.72
137       151  Teclado    25.00000         1471.75 2023-10-28       36793.75
138       152  Teclado    26.00000          183.43 2025-03-20        4769.18
286       305  Teclado    15.00000          233.59 2024-12-16        3503.85
312       332  Teclado    21.00000         1135.01 2025-03-07       23835.21
320       340  Teclado    28.00000          665.65 2025-02-24       18638.20
339       360  Teclado    16.00000          300.38 2025-08-05        4806.08
379       401  Teclado    25.00000         1257.56 2023-03-07       31439.00
470       496  Teclado    14.00000          717.33 2025-07-15       10042.62
480       506  Teclado    27.00000         1027.91 2023-02-13       27753.57
507       535  Teclado    17.00000          602.49 2023-06-22       10242.33
516       545  Teclado    11.00000          638.11 2025-09-23        7019.21
523       553  Teclado    27.00000          380.90 2024-02-08       10284.30
529       559  Teclado    24.00000          251.94 2024-03-01        6046.56
544       574  Teclado    17.00000          985.04 2024-07-17       16745.68
549       579  Teclado    17.00000         1479.28 2024-01-06       25147.76
571       602  Teclado    20.00000          460.50 2023-09-19        9210.00
616       649  Teclado    11.00000           47.02 2023-01-12         517.22
644       680  Teclado    17.00000         1443.00 2023-08-01       24531.00
651       687  Teclado    18.00000         1174.57 2023-08-26       21142.26
661       697  Teclado    29.00000          571.98 2023-01-07       16587.42
664       700  Teclado    24.00000           44.12 2025-08-18        1058.88
685       721  Teclado    21.00000           80.22 2025-08-18        1684.62
723       759  Teclado    24.00000           74.73 2024-11-13        1793.52
796       837  Teclado    16.00000         1043.42 2023-04-12       16694.72
814       856  Teclado    20.00000          675.60 2024-08-15       13512.00
848       894  Teclado    29.00000          891.09 2024-11-11       25841.61
857       904  Teclado    17.00000           47.63 2023-12-06         809.71
896       944  Teclado    25.00000          919.71 2025-02-04       22992.75
922       971  Teclado    14.00000          841.53 2023-04-27       11781.42

     Mes_Venda    Categoria
62           3  Periféricos
63           7  Periféricos
97           3  Periféricos
108         10  Periféricos
114         10  Periféricos
137         10  Periféricos
138          3  Periféricos
286         12  Periféricos
312          3  Periféricos
320          2  Periféricos
339          8  Periféricos
379          3  Periféricos
470          7  Periféricos
480          2  Periféricos
507          6  Periféricos
516          9  Periféricos
523          2  Periféricos
529          3  Periféricos
544          7  Periféricos
549          1  Periféricos
571          9  Periféricos
616          1  Periféricos
644          8  Periféricos
651          8  Periféricos
661          1  Periféricos
664          8  Periféricos
685          8  Periféricos
723         11  Periféricos
796          4  Periféricos
814          8  Periféricos
848         11  Periféricos
857         12  Periféricos
896          2  Periféricos
922          4  Periféricos